config:
  security:
    oauth:
      client:
        id: stocktaking-client-id
        secret: Ks2-Lsm54.Qmcn
      jwt:
        key: omfospmfomwpoPDMSPEOFMPOMPOmpomfp.seomfpowsmpfoampovmrpovmpo.spfonvpompvioqempvin.dfinvpinfpvinaspivnpid.fnvpidnf.pvindfpivnpdifnvpin76543567
time-validity:
  token: 3600
  refresh-token: 3600
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_stocktaking?serverTimezone=America/Mexico_City&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none